name : 'basic'

#특정 액션에서만 실행 (브랜치, 파일 경로도 지정 가능)
on: push 

jobs:
  #job 이름
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest']
        node: [ '16.x', '18.x' ]

    #실행하는 os 지정
    runs-on: ${{ matrix.os }}

    #실제 구동 부분
    steps:
    - name: Say Hello from OS - ${{ matrix.os }}
      shell: bash
      run: |
        echo "Hello World from ${{ matrix.os }}"

    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: '${{ matrix.node }}'
  
    - name: Run only on Ubuntu
      if: matrix.os == 'ubuntu.latest'
      shell: bash
      run: |
        echo "Hello from ${{ matrix.os }}"
