name : 'basic'

#특정 액션에서만 실행 (브랜치, 파일 경로도 지정 가능)
on: push 

jobs:
  #job 이름
  first-job:
    name: 'First Job'

    #실행하는 os 지정
    runs-on: ubuntu-latest

    #실제 구동 부분
    steps:
    - name: Say hello world 1
      shell: bash
      env:
        STEP_VALUE_1: "This is a env var from the step lv. #1"
      run : |
        generatedValue1=$(echo $RANDOM)

        echo "GEN_VALUE_1=$generatedValue1" >> $GITHUB_ENV
    - name: Say hello world 2
      shell: pwsh
      env:
        STEP_VALUE_2: "This is a env var from the step lv. #2"
      run: |
        $generatedValue2=$(Get-Random -Max 99999)

        echo "GEN_VALUE_2=$generatedValue2" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Get Hello world values
      shell: bash
      run: |
        echo "GEN_VALUE_1: $GEN_VALUE_1"
        echo "GEN_VALUE_2: ${{ env.GEN_VALUE_2 }}"